/**
 * @description       : This exception is used to mark gaps in example code where a work is in progress or it's not practical for the purpose of
*                       examples to spell out the remaining details of an implementation.
 * @author            : Tom Zarr
 * @group             : Salesforce Commerce Partner Delivery Success (2024)
 * @last modified on  : 03-11-2024
 * @last modified by  : Tom Zarr
**/
public with sharing class NotImplementedException extends Exception { }